Error: here is a test error

Traceback:
1: stop("here is a test error")

